// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMAihqtz6yF_M974Erhx6x7yzZnffnXrs',
    appId: '1:858603345303:web:e5c45f0262646f856ae0d2',
    messagingSenderId: '858603345303',
    projectId: 'autograph-83959',
    authDomain: 'autograph-83959.firebaseapp.com',
    storageBucket: 'autograph-83959.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLB36vRCa26c59X9bETMosgTIYP2U6IM8',
    appId: '1:740185525778:android:a5d22d2544d4a497e8d2cb',
    messagingSenderId: '740185525778',
    projectId: 'autograph-5',
    storageBucket: 'autograph-5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRZZBp4b5KxYCa_aSxJLgBvZTXet-gCA0',
    appId: '1:740185525778:ios:b3378822994504cce8d2cb',
    messagingSenderId: '740185525778',
    projectId: 'autograph-5',
    storageBucket: 'autograph-5.firebasestorage.app',
    iosBundleId: 'com.autograph.autograph',
  );
}
