// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVFL1hrKpdrUmCTXvOAXeM8QLE4iWrQ_U',
    appId: '1:740185525778:web:0ae925873bb709cbe8d2cb',
    messagingSenderId: '740185525778',
    projectId: 'autograph-5',
    authDomain: 'autograph-5.firebaseapp.com',
    storageBucket: 'autograph-5.firebasestorage.app',
    measurementId: 'G-SD8VW3MVP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLB36vRCa26c59X9bETMosgTIYP2U6IM8',
    appId: '1:740185525778:android:a5d22d2544d4a497e8d2cb',
    messagingSenderId: '740185525778',
    projectId: 'autograph-5',
    storageBucket: 'autograph-5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRZZBp4b5KxYCa_aSxJLgBvZTXet-gCA0',
    appId: '1:740185525778:ios:b3378822994504cce8d2cb',
    messagingSenderId: '740185525778',
    projectId: 'autograph-5',
    storageBucket: 'autograph-5.firebasestorage.app',
    iosBundleId: 'com.autograph.autograph',
  );
}
